apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: myappspa
  namespace: myapp
spec:
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: myappspa
    spec:
      containers:
        - name: myappspa
          image: tomasslaviksec001.azurecr.io/myappspa:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
